package common.util.response;

public enum Notification
{
    LOGIN_ERROR, LOGIN_SUCCESS,
    REGISTER_ERROR, REGISTER_SUCCESS,
    QUIT_ERROR, QUIT_SUCCESS,
    GET_ERROR, GET_SUCCESS,
    ADD_SUCCESS, ADD_ERROR,
    UPDATE_SUCCESS, UPDATE_ERROR,
    REMOVE_SUCCESS, REMOVE_ERROR,
    UNKNOWN_COMMAND_ERROR;
}
